---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
framework_version: latest
serverless_language:
polling_url: https://services2.arcgis.com/HdTo6HJqh92wn4D8/arcgis/rest/services/Air_Quality_and_Pollen_Count_1/FeatureServer/0/query?outFields=*&where=1%3D1&orderByFields=ReportDateTime%20desc&f=geojson&resultRecordCount=18
polling_headers: ''
polling_body: ''
id: 93912
oauth_enabled: 'false'
oauth_pkce_enabled: 'no'
oauth_authorize_url: ''
oauth_token_url: ''
oauth_scopes: ''
oauth_scope_separator: ''
oauth_refresh_url: ''
oauth_auth_params: ''
oauth_token_headers: ''
oauth_token_site: ''
oauth_token_params: ''
oauth_token_request_auth_method: ''
oauth_body_format: ''
oauth_token_response_metadata: ''
oauth_authorization_method: ''
oauth_refresh_params: ''
oauth_token_field_name: ''
oauth_expiry_field_name: ''
oauth_expiry_strategy: ''
oauth_fixed_expiry_ms: ''
custom_fields:
- keyname: author_bio
  name: About This Plugin
  field_type: author_bio
  category: environment
  description: Pollen and air quality report from the Metro Nashville Health Department.
  github_url: https://github.com/stephenyeargin/trmnl-nashville-pollen-aqi
  learn_more_url: https://www.nashville.gov/departments/health/environmental-health/air-pollution-control/daily-aqi-and-pollen-count
  email_address: stephen@yearg.in
name: Nashville Pollen & Air Quality
description: Local allergy & smog forecast
refresh_interval: 1440
